### ISSUE TITLE
Las suscripciones de clarificaciones tienen parámetros inconsistentes

### ISSUE THREAD

**Issue by frcepeda** [omegaup/omegaup#1736]
Al suscribirse a eventos de clarificaciones, a veces el `clarification_id` llega como string y a veces como número.

**Comment by lhchavez** [comment]
Esto nada más es encontrar dónde nos falta hacer un cast de cadena a entero en `ClarificationController.php`

**Comment by sarvesh211999** [comment]
can anybody explain what does this mean "subscribing to clarification events" ??

**Comment by lhchavez** [comment]
sure! if you try to open a websocket with WebSockets (ws://localhost:8080/events/?filter=all-events), or visiting a contest as an admin (you'll get a green little circle next to the contest name), sometimes the datatype of `clarification_id` is String (because PHP) and sometimes it's Integer. This is fine for languages that are a bit loosey-goosey with their type system (like JavaScript), but for others where they take this more seriously (like Haskell), it's a bit problematic. This can be confirmed by opening the Chrome Developer Tools prior to visiting the contest and inspecting the packets of the WebSockets connection.

Whenever a clarification is updated, it goes through here: https://github.com/omegaup/omegaup/blob/master/frontend/server/controllers/ClarificationController.php#L226

so! the only thing that IIUC needs to be done is to change this line https://github.com/omegaup/omegaup/blob/800b9c81f714c891ec6277558d045b86c8f1aa65/frontend/server/libs/Broadcaster.php#L16 to add an explicit cast to `int` for the `clarification_id`.

**Comment by sarvesh211999** [comment]
Where I can see data type of clarification_id ??

**Comment by sarvesh211999** [comment]
Whenver a page where clarification is reloaded the JSON response that contains all the clarifications to be displayed contains the clarification_id as string . So I am not getting from where this JSON response is coming?
