### ISSUE TITLE
El dropdown de detalles de envíos está incompleto

### ISSUE THREAD

**Issue by frcepeda** [omegaup/omegaup#1738]
## Comportamiento Esperado

Cuando le doy detalles a un envío, puedo ver el nombre de cada caso y su veredicto.

## Comportamiento Actual

La tabla está vacía.

![image](https://user-images.githubusercontent.com/468211/36064096-7b5439ae-0e4b-11e8-9ace-23cf8cf6dff0.png)

## Pasos para reproducir (para bugs)

Abrir un concurso en el que eres administrador, ir a envíos, y luego detalles de los envíos.

**Comment by lhchavez** [comment]
El problema es que el código que lo renderea https://github.com/omegaup/omegaup/blob/15752e7b23dcb27fd287456ca1d6571b096c4f93/frontend/www/js/omegaup/arena/arena.js#L1469 está lleno de cosas legacy D: creo que mejor hay que migrar eso a Vue para poderlo poner bonito y que esté más fácil de razonar acerca de qué hace exactamente.

**Comment by lhchavez** [comment]
@CarlosCordova18 how does this one sound?

**Comment by CarlosCordova18** [comment]
Would give this a look, assign it to me :D

**Comment by lhchavez** [comment]
Assigned to @CarlosCordova18 :D

**Comment by CarlosCordova18** [comment]
Hi, @lhchavez with "legacy things" you mean jQuery and all the old stuff you're planning to migrate to Vue. Right?

Please review the workflow I'm creating for solving this issue, and make the corrections if needed to begin coding:
- Create the Run Details' component in `./frontend/www/js/omegaup/components/arena/`
- Modify the smarty template (https://github.com/omegaup/omegaup/blob/master/frontend/templates/arena.rundetails.tpl) to be used just for the Vue component.
- Create the Vue Instance for the Run Details' component inside of the `displayRunDetails(...)` method, to recreate the component each time the method is called. Similar to: https://github.com/omegaup/omegaup/blob/3f91ad651584d873ece82573b767f54df9acd79c/frontend/www/js/omegaup/arena/arena.js#L976 

Thanks :smile:

**Comment by lhchavez** [comment]
That workflow sounds good! There's an alternatitive to your second step, replace these three `{include file='arena.rundetails.tpl'}` with the div where the Vue component will be mounted and delete `arena.rundetails.tpl` altogether!

https://github.com/omegaup/omegaup/search?utf8=%E2%9C%93&q=arena.rundetails.tpl&type=

**Comment by CarlosCordova18** [comment]
Hey @lhchavez this is what I see when entering to "Runs" on a contest which I'm the admin.
![captura de pantalla de 2018-03-13 08-37-02](https://user-images.githubusercontent.com/20785082/37344969-d4c6ffce-2699-11e8-96c4-3fe412f52e49.png)

**Comment by CarlosCordova18** [comment]
Anyways, I managed to get into rundetails view by going to problem's run details.

**Comment by CarlosCordova18** [comment]
Hi, @lhchavez or @frcepeda, do you have any view of how the cases table should look like if being OK?
I have migrated all to Vue Js except the Cases table which I don't understand very well.

**Comment by lhchavez** [comment]
what we want is each case to have an entry in that table. with the case name in the **Case** column and the verdict in the **Verdict** column. but since there are problems with lots of cases, we would like to make the list of cases for an individual group to be collapsible (and that's the way it used to show :cry: ). the groups don't have a case name nor verdict.

so when everything is collapsed, it should look like the screenshot that is posted, but with dropdown buttons next to each row.

**Comment by CarlosCordova18** [comment]
Hi @lhchavez finally I found a way to display the table correctly in Vue Js (also I learned a lot doing that).
Could you please verify if it looks good?
https://docs.google.com/document/d/17xC7YamFHKusml2KkQNNuQGnCGY389ViDLcfUKjpmPQ/edit?usp=sharing

After your confirm I will make the PR, but I need to be sure before, because everytime I re run the `vagrant up` command after restarting my laptop, webpack starts to fail and I need to destroy the machine.

**Comment by lhchavez** [comment]
Thanks for your (once again) very detailed document!

Would it be possible to merge the column titles?

```
+---------------------------------------+
|Grupo      Caso    Veredicto  Score    |
+---------------------------------------+
|easy        A                   0.4/0.4|
|           easy.01   AC         0.4/0.4|
+---------------------------------------+
|medium      v                 0.55/0.55|
+---------------------------------------+
|sample      v                 0.05/0.05|
+---------------------------------------+
```

(where `v` and `A` are the "dropdown" arrows in your screenshots).

With that I think we should be good :D Have you shared the output of webpack once it gets into the bad state on Slack? We should really try to get that fixed since that sounds super annoying u_u.

**Comment by CarlosCordova18** [comment]
I've got it!
I'll make the PR now, hope won't have many errors.
![Done!](https://user-images.githubusercontent.com/20785082/38101812-ff4f1cb8-3346-11e8-824b-e07c73a6dcc4.png)
