### ISSUE TITLE
[Color Hierarchy] make apiProfile() return user's color

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#1771]
The algorithm to compute the user's color in described in the design doc:
https://docs.google.com/document/d/1R14hS-6TEhE34Aw3Pu_85jqIZjCyxVx6fiCHL8cvLg0/edit#

**Comment by heduenas** [comment]
Cost estimate: 4 hours including tests.

**Comment by randika96** [comment]
Can you tell me where I can find apiProfile()?  Then I can start work on this.

**Comment by heduenas** [comment]
It's right here:
https://github.com/omegaup/omegaup/blob/004156793d50b97c9fc92af19077d784cd857b89/frontend/server/controllers/UserController.php#L1222

**Comment by randika96** [comment]
i will start working on this issue

**Comment by lhchavez** [comment]
assigned! let us know if you need any help.

**Comment by randika96** [comment]
As a solution for this I am thinking of declaring a function to calculate the appropriate color which takes the marks as an argument and return the color. In case of that can you tell what is the best place for the place this method.  And call the method inside the apiProfile().
Can you tell me where I can find a class for user?

**Comment by lhchavez** [comment]
It's probably better to have this be a CSS classname instead of a hardcoded color. I've already sent https://github.com/omegaup/omegaup/pull/1781 out so that the cron job that calculates the user ranks also calculates the cutoff points and the classnames. You'll need to re-fetch master to get that code, and run `./stuff/db-migrate.py migrate` to install the new table.

Since it's a cronjob, it's run on a schedule, so you'll want to run it manually for testing:

```shell
ubuntu@ubuntu-xenial:/opt/omegaup$ sudo su -c '/opt/omegaup/stuff/cron/update_user_rank.py'
2018-02-25 16:00:44,318:update_user_rank.py:Started
2018-02-25 16:00:44,335:update_user_rank.py:Updating accepted stats for problems...
2018-02-25 16:00:44,336:update_user_rank.py:Updating user rank...
2018-02-25 16:00:44,338:update_user_rank.py:Updating ranking cutoffs...
2018-02-25 16:00:44,340:update_user_rank.py:Done
```

The method to calculate the classname, given that it will perform some interaction with the database, should go in the Data Access Objects class [`Users.dao.php`](https://github.com/omegaup/omegaup/blob/master/frontend/server/libs/dao/Users.dao.php).

**Comment by randika96** [comment]
How is the marks are stored along with user?

**Comment by lhchavez** [comment]
They are stored in the [`User_Rank`](https://github.com/omegaup/omegaup/blob/029b0be9f386eae134ade319fa88ad62b8bfa1a8/frontend/database/schema.sql#L707) table. @heduenas will assist you further if needed.

**Comment by lhchavez** [comment]
The change to add the table is merged. If you have not modified the code yet, you can do `git fetch upstream master && git reset --hard origin/master`. If you have, you need to `git stash` first and after you run the previous command, do `git stash pop`.

**Comment by randika96** [comment]
I have not modified the code yet. still I am understanding the relevant information. I came up with algorithm to calculate colors when marks are given.

**Comment by lhchavez** [comment]
@randika96 does that algorithm use the recently-created `User_Rank_Cutoffs` table? Otherwise it's going to be way too slow since MySQL does not have an efficient way of calculating percentiles and it'll become prohibitively expensive to run with the production data set.

feel free to go to the Slack if you want to discuss this further.

**Comment by randika96** [comment]
No, Can you tell me where I can find that table "User_Rank_Cutoffs"?  Does this table already calculated the appropriate class name for given user ID? or Do I have to do it? 
Can you tell me how to merge the new code which include new table with my existing vm running file?

**Comment by randika96** [comment]
As a conclude what I am going to implement, 

- Declare the function which calculate the css class name in class Users.dao. Takes user id as an argument and return the class name.

- call the above function inside the apiProfile() function and return user along the class name.

Is this approach is okay or can you tell where should I change?

**Comment by lhchavez** [comment]
yes, it's in the [`schema.sql`](https://github.com/omegaup/omegaup/blob/8855dcb75086722877a887d146402a88ba94b9d8/frontend/database/schema.sql#L746). it only has the relationship between score cutoffs and classnames. given a user id, you can use this table to get the classname for the largest score such that it's lower than the user's score.

instructions to merge are in my previous comment in this same thread.

**Comment by randika96** [comment]
Than you for your guidance, I will start to implement this.

**Comment by randika96** [comment]
@lhchavez  git fetch upstream master && git reset --hard origin/master I treid this command to merge the code but it did not work.

**Comment by lhchavez** [comment]
ah, sorry, there was a typo! the correct command should be ` git fetch upstream master && git reset --hard upstream/master`
