### ISSUE TITLE
Potential CSRF and XSS in problem statement

### ISSUE THREAD

**Issue by SpaceWhite** [omegaup/omegaup#1878]
## Current behaviour
Problem statement reproduced by markdown html is not encoded, so that anyone can input a malicious html code in the problem statement

## Expected behaviour
Problem statement should be encoded to prevent CSRF

## How to reproduce this issue
1. Create a problem
2. Input html code like `<script>`, `<img>`, `<script>` into the markdown
3. View the problem

Currently not all XSS code is working because program execution is protected by CSP. But since the CSP `script-src 'self'` it can somehow be bypassed. Refer this  [Article](https://medium.com/@tbmnull/making-an-xss-triggered-by-csp-bypass-on-twitter-561f107be3e5) for more details.

**Comment by SpaceWhite** [comment]
@lhchavez I think this should be solved ASAP :(

**Comment by lhchavez** [comment]
Fortunately our CSP rules are a bit more robust than that and don't allow for the PoC you mention:

```
Refused to load the script 'http://analytics.twitter.com/tpm?tpm_cb=alert(document.domain)' because it violates the following Content Security Policy directive: "script-src 'self' https://www.google.com https://apis.google.com https://www.gstatic.com https://js-agent.newrelic.com https://bam.nr-data.net https://ssl.google-analytics.com".
```

It's still something we do want to fix ASAP because even though the whitelisted domains do their fair share of XSS protection (like escaping output that could be interpreted as JS), we don't have a guarantee that they won't drop the ball like the twitter analytics callback.

Thanks for reporting this!

**Comment by lhchavez** [comment]
El código que convierte [Markdown a HTML](https://github.com/omegaup/pagedown) debería de quitar los tags peligrosos.

**Comment by SpaceWhite** [comment]
@lhchavez  Actually pagedown has sanitizeTag function implemented https://github.com/omegaup/pagedown/blob/b3b3cab1c4c118faceac330a4a8813c925e3fab4/Markdown.Sanitizer.js#L30.

**Comment by lhchavez** [comment]
Argh, good point, I messed up the link. It should have pointed to https://github.com/omegaup/omegaup/blob/master/frontend/server/libs/third_party/Markdown/markdown.php (this is the one used prior to saving the HTML to disk) instead of https://github.com/omegaup/pagedown (this is only used to preview).

Maybe we should stop pre-rendering the HTML version and always use the JS one? It might be better for everyone because the JS one (used in https://omegaup.com/redaccion.php) is already immune to this attack since we do use `sanitizeTag`.

**Comment by SpaceWhite** [comment]
@lhchavez Yes, I think that would be a good idea. Rendering the problem_statement from JS like the redaccion.php. So the API will be called twice when user want to view the problem? (First : Call the API in tpl (to retrieve problem details without problem statement), Second : Call the API in vue (to retrieve problem statement)

**Comment by lhchavez** [comment]
Most of the work has been done, we only miss merging https://github.com/omegaup/omegaup/pull/1946 and we should be good!

**Comment by prondubuisi** [comment]
Jr
