### ISSUE TITLE
System admin potential CSRF target on change password API

### ISSUE THREAD

**Issue by SpaceWhite** [omegaup/omegaup#1902]
## Current behaviour
Currently admin can directly change user password without any additional authentication (such as old_password, captcha, etc). This can be used as a target of CSRF.

Example: omegaup.com/api/user/changepassword?user=user1&password=maliciouspass

## Expected behaviour
There should be some additional authentication (maybe captcha) to mitigate CSRF when admin want to attempt password changes

**Comment by lhchavez** [comment]
welp

**Comment by lhchavez** [comment]
Turns out this particular API is only used in one place, and we already have a better alternative when there is a previous interaction with the support team, so don't need it anymore \o/ but our APIs still don't have any CSRF protection, which is kind of scary. I'll fix this quickly (by simply not using this API at all) and open a new one to enable CSRF protection across the board.
