### ISSUE TITLE
"This mail is already in use. Try again." error while registering

### ISSUE THREAD

**Issue by kylelobo** [omegaup/omegaup#2352]
## Expected behaviour
If a user enters valid credentials, and if the email they use is an unregistered email, he / she should be able to create an account.

## Current behaviour

While trying to create a new account on omegaUp, I enter my credentials, but, when I click on Register, I first get a message saying "error" and when I re-click, I get a message saying "This mail is already in use. Try again." 

I have cross-checked to see if the email actually exists by going to "Forgot your password?" and entering the email. However, I get a message saying "Unverified user".

## Steps to reproduce (for bugs)
1) Go to - https://omegaup.com/login/
2) Enter some credentials in the register section.
3) Click on register.

## Context
I cannot solve problems / partake in contests until I create an account.

## Your environment
+ I have tried this on Firefox 64.0 (Ubuntu 16.04) as well as on Chrome 71.0.3578 (Android 9)
+ Link to the site where this problem happens: 
https://omegaup.com/login/
+ Screenshots:

#### The first time I click on Register:
![login - error](https://user-images.githubusercontent.com/25124502/52001769-39a98600-24e6-11e9-9ba7-9d18796978cb.png)

#### The second time I click on Register:
![login - mail already in use](https://user-images.githubusercontent.com/25124502/52001770-3e6e3a00-24e6-11e9-9c1e-de8dbfda828f.png)

#### Trying to check if the email actually exists:
![recover password - unverified user](https://user-images.githubusercontent.com/25124502/52001774-40d09400-24e6-11e9-8ff6-c80dbdb588ee.png)

**Comment by SpaceWhite** [comment]
@kylelobo  I can't reproduce the error. And the registration should work fine. (You could try create fake account here https://sandbox.omegaup.com). The sandbox is used for testing purpose and it should work similar with current omegaUp platform. Probably you did click the register twice in the frontend which results in triggering the API twice.(https://github.com/omegaup/omegaup/blob/d2180611dad2a5c755b6ad5826d10d8ca9ba9f3e/frontend/templates/login.tpl#L69) 

@lhchavez IMHO how about instead of using raw POST from post. We let javascript (with double firing prevention) to call user apiCreate?

**Comment by SpaceWhite** [comment]
I could reproduce this error by using guerilla mail email. This errors appear only affect only omegaup.com (I could not reproduce it in local and sandbox) and when user input a very long email address. The error is caused by [User apiCreate API](https://github.com/omegaup/omegaup/blob/d2180611dad2a5c755b6ad5826d10d8ca9ba9f3e/frontend/server/controllers/UserController.php#L41).  My speculation is that error reproduced when API create calls [sendVerificationEmail](https://github.com/omegaup/omegaup/blob/d2180611dad2a5c755b6ad5826d10d8ca9ba9f3e/frontend/server/controllers/UserController.php#L191) function. @lhchavez @kylelobo

**Comment by lhchavez** [comment]
it's true that we may need to do a better job of ensuring the transactionality and idempotency of user creation, but i don't see any logs related to errors during user creation :(
