### ISSUE TITLE
[BUG] No se puede editar el valor de un problema, cuando un concurso tiene la cantidad máxima de problemas

### ISSUE THREAD

**Issue by Apocryphon-X** [omegaup/omegaup#5974]
## Comportamiento Esperado

Poder editar el puntaje de un problema incluso cuando el problemario este lleno.
![image](https://user-images.githubusercontent.com/40130428/141010354-abfbc8a3-a11e-4c2e-8bd7-d64571f743ea.png)

## Comportamiento Actual

Si el concurso esta en su capacidad maxima de problemas, y todos los problemas ya tienen envios; se vuelve imposible editar el puntaje de algún problema en especifico.

![image](https://user-images.githubusercontent.com/40130428/141011080-25d865f2-2870-4ddf-b3e5-99b6fd9406d1.png)

## Pasos para reproducir 

Link donde el problema ocurre: `https://omegaup.com/contest/<ALIAS>/edit/`

1. Llenar un concurso con la cantidad maxima de problemas.
2. Hacer que cada uno tenga minimo 1 envio.
3. Tratar de editar el puntaje de cualquier problema.

## Ambiente

<html>
<body>

Google Chrome | 95.0.4638.69 (Build oficial) (64 bits) (cohort: Stable)
-- | --
Revisión | 6a1600ed572fedecd573b6c2b90a22fe6392a410-refs/branch-heads/4638@{# 984}
Sistema operativo | Windows 11 Version Dev (Build 22494.1000)
JavaScript | V8 9.5.172.25
User-agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36
Línea de comandos | "C:\Program Files\Google\Chrome\Application\chrome.exe" --flag-switches-begin --flag-switches-end
Ruta del ejecutable | C:\Program Files\Google\Chrome\Application\chrome.exe

</body>
</html>

**Comment by Apocryphon-X** [comment]
Nota al Resumen: No se esta agregando ningún problema nuevo, simplemente se quiere editar el valor de uno ya existente en el concurso. El panel interpreta la acción como si se estuviese agregando un problema adicional (cuando en realidad solo se esta editando uno de los que ya estan).

**Comment by Aritra8438** [comment]
@pabo99, I have seen this issue earlier, but the translation is not so good. Can you explain a bit, and if possible can you assign this to me.

The translation is following:
<img width="959" alt="image" src="https://github.com/omegaup/omegaup/assets/64671908/493dbaac-e37b-414b-b638-1d6232008fc6">

**Comment by pabo99** [comment]
It is correct: "Issue" means "Problem"

And this is what is happening:

In `apiAddProblem`, we have a precondition to add new problems: the number of problems must not exceed a certain limit defined in a constant called `MAX_PROBLEMS_IN_CONTEST`.

The issue arises when we want to edit the value of each problem in the contest, as this action also calls `apiAddProblem`, where it validates if the problem already exists in the problemset, if so, only updates the object.

The possible solution would be to retrieve the `ProblemsetProblems` object just before the exceeded limit validation, and right there add a new validation if the problem already exists in the problemset.

Also, this object could be passed to the `updateProblemsetProblem` function as a parameter so that it doesn't need to be obtained again.

I hope it's clearer now.
