### ISSUE TITLE
[BUG] Bullets in Contest Page

### ISSUE THREAD

**Issue by anmode** [omegaup/omegaup#6536]
## Comportamiento Esperado
![Screenshot from 2022-04-15 11-36-07](https://user-images.githubusercontent.com/88332977/163528612-4e8d68d2-e4e9-4449-ad9a-c49e476c57a2.png)
Bullet should be equal to intructions(Rules).

## Comportamiento Actual

![Screenshot from 2022-04-14 20-1-34](https://user-images.githubusercontent.com/88332977/163528496-1094ccc7-15e3-4323-b113-c3c7d7d53cb7.png)
I contest page in most of contest one bullet is extra.

## Pasos para reproducir (para bugs)

1. Go to https://omegaup.com/
2. Open any contest (In most of u will find this bug)
3. See Rules

## Contexto

For Better UI/UX bullet should be equal to number of given instruction(Rules) in a contest.

## Tu ambiente

*Incluye los detalles relevantes acerca del ambiente en el que reprodujiste
este bug*

* Nombre del navegador (e.g. Chrome):
* Sistema Operativo y versión (Ubuntu 21.10):
* Link al sitio en el que este problema pasa:https://omegaup.com/arena/INBRH22010314/

**Comment by anmode** [comment]
I know how to solve it! Please assign it to me I will generate  PR then! Thanks

**Comment by mohdabbas955** [comment]
Can you please assign me this issue.

**Comment by ShivamJhaa** [comment]
@pabo99 Hi, I want to work on this issue. Can you please assign me this? 
I have already completed phase 1 of GSoC application. (OmegaUp Username: sssvjha)

**Comment by heduenas** [comment]
Thank you @ShivamJhaa  for completing phase 1 and for confirming your omegaup username! I've assigned the issue to you.

**Comment by ShivamJhaa** [comment]
> Thank you @ShivamJhaa for completing phase 1 and for confirming your omegaup username! I've assigned the issue to you.

Hi, I am not able to access this page on local server, whenever I create a contest then I am enrolled in the contest by default and hence when I click on the contest I goes directly to the problem page instead of rules page:
![Screenshot from 2023-03-04 12-47-46](https://user-images.githubusercontent.com/86483059/222881846-7d53f680-aeaf-4343-8a4b-d5218a6f2756.png)

Is there a way to unregister ourselves from the contest that we create, or load some dummy contest not created by me?
