### ISSUE TITLE
Agregar un texto que explique por que esta desactivada la opción de concurso por equipos

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#6961]
Se desactiva cuando se esta editando in concurso existente.

**Comment by sasirekhamurakonda** [comment]
Hey @heduenas Could you assign this issue to me I would like to contribute to this issue.
And Could you explain me a little about the issue

**Comment by heduenas** [comment]
Hi @sasirekhamurakonda, have you had a chance to complete the first phase of the application process? https://omegaup.com/arena/gsoc2023-2 If yes, what's your username so I can confirm.

**Comment by Manish-Mulchandani** [comment]
Hi @heduenas, Could you explain a little about the issue. 
Regarding the application process, I have completed the first phase, Username - Manish

**Comment by pabo99** [comment]
Explanation:

In the "Contest > Edit" view
![image](https://user-images.githubusercontent.com/3230352/229427312-814219a7-9321-4bbc-86a3-512e5365ccbf.png)
, you can find a checkbox labeled "Contest for teams". 

However, this checkbox is disabled because this specific type of contest requires a teams group when the checkbox is selected. Conversely, individual users are required in the list of contestants when the checkbox is not selected. Currently, it is not possible to mix these two identities. 

To fix this issue, the contributor should modify the text to reflect this explanation.

Perhaps @heduenas or @tvanessa can provide the updated text to be displayed.

**Comment by Manish-Mulchandani** [comment]
For the new text, I was thinking "If activated, the contest can only be accessed by teams instead of users or identities. The teams have to be added to a teams group. Teams Enable option is disabled when editing an existing contest"

**Comment by subhajit20** [comment]
@pabo99 is this issue still open?

**Comment by pabo99** [comment]
> @pabo99 is this issue still open?

That's correct! This issue can be assigned to you or anyone else who wants to contribute to us!

**Comment by pabo99** [comment]
Ping to @heduenas , @tvanessa

**Comment by subhajit20** [comment]
@tvanessa Hey what would be appropriate text beside the checkbox ?

**Comment by axsseldz** [comment]
@pabo99 @heduenas @tvanessa Yo podria resolver este issue si aun nadie esta trabajando en ello. (:
