### ISSUE TITLE
[FEATURE] Remove or review dead code in `ephemeral.js`

### ISSUE THREAD

**Issue by HNOONa-0** [omegaup/omegaup#7652]
We have the following piece of code for `hashchange` event:
https://github.com/omegaup/omegaup/blob/5513fb1f507c5f6f3b0eb432d6ad19e06c5c0590/frontend/www/js/omegaup/grader/ephemeral.js#L985-L1053

This code never actually execute beyond the first `if` statement. This is because `window.location.hash` references link to embed IDE `iframe`, which is always empty (not actual link of the page that is the parent window). Here is a picture of what I mean.
![image](https://github.com/omegaup/omegaup/assets/59091536/b94f2ba8-1534-4c71-931f-c35a1913d2b3)

It's probably safe to remove.

**Comment by pabo99** [comment]
This code might indeed be necessary if we use it in a different context than the one shown in your example.

What I mean is the following case: We have a different way of accessing the ephemeral component, which is by visiting the URL: http://localhost:8001/grader/ephemeral.

If you add a hash to this URL, you will now be accessing the code you intend to remove, since in this case, it is not being embedded in an `iframe`, but rather you are directly displaying the component.

![image](https://github.com/omegaup/omegaup/assets/3230352/ffc15821-a6e0-43b8-a998-9fe03bc7ef92)

So, for now, you can leave this code as it is.

**Comment by HNOONa-0** [comment]
That makes sense. Alright then, closing this.
