### ISSUE TITLE
[FEATURE] Unify the supported languages lists

### ISSUE THREAD

**Issue by pabo99** [omegaup/omegaup#7810]
Currently, we have a list of supported languages to solve problems on the omegaUp platform. The issue that may arise is inconsistency in different views because we have several places where the lists are stored. For example, we have this list in TypeScript: https://github.com/omegaup/omegaup/blob/3d5330701c8dfe3ff3cd828754974fe1d7150aea/frontend/www/js/omegaup/graderv2/util.ts#L63-L221

and we have this other one in PHP: https://github.com/omegaup/omegaup/blob/3d5330701c8dfe3ff3cd828754974fe1d7150aea/frontend/server/src/Controllers/Run.php#L19-L43

And there may be other places we haven’t identified.

The intention is to unify these two lists to display the same information in all places where these lists are shown.

**Comment by HNOONa-0** [comment]
@pabo99 I have a couple of ideas:
1- Add a payload that would return all supported languages from `php` then store those languages and refer to them as necessary when the application loads.
2- Add a `languages.json` that would be "single source of truth" for supported languages. I'm more lenient towards this approach because we can comfortably hold more information about each language and no api calls are necessary.
